ALTER TABLE WFS_NODE ADD (owner VARCHAR(255));
ALTER TABLE WFS_NODE_GROUP ADD (owner VARCHAR(255));
ALTER TABLE WFS_WORKFLOW ADD (owner VARCHAR(255));
ALTER TABLE WFS_SCHEDULE ADD (owner VARCHAR(255));
ALTER TABLE WFS_WORKFLOW_JOB ADD (owner VARCHAR(255));
ALTER TABLE WFS_SCHEDULE_JOB ADD (owner VARCHAR(255));

ALTER TABLE WFS_WORKFLOW ADD (app_name VARCHAR(40));
ALTER TABLE WFS_SCHEDULE ADD (app_name VARCHAR(40));
